package br.gov.go.agr.models;


import jedi.db.models.*;

public class Cidade extends Model {

    private static final long serialVersionUID = 2154631841600429923L;

    @CharField(max_length = 50)
    private String nome;

    @ForeignKeyField
    private Estado estado;

    @CharField(max_length = 10)
    private String cep;

    public static Manager objects = new Manager(Cidade.class);

    public Cidade() {

    }

    public Cidade(String nome, Estado estado, String cep) {
        this.nome = nome;
        this.estado = estado;
        this.cep = cep;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Estado getEstado() {
        return estado;
    }

    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    public String getCEP() {
        return cep;
    }

    public void setCEP(String cep) {
        this.cep = cep;
    }

    public String unicode() {
        return String.format("%s [%s]", nome, estado.getNome());
    }

    // Generated by Jedi ORM
    public QuerySet<Contato> getContatoSet() {
        return Contato.objects.getSet(Cidade.class, this.id);
    }
}
