package br.gov.go.agr.models;


import jedi.db.models.*;

public class Estado extends Model {

    private static final long serialVersionUID = 3468867936730125023L;

    @CharField(max_length = 50)
    private String nome;

    @CharField(max_length = 50)
    private String sigla;

    @ForeignKeyField
    private Pais pais;

    public static Manager objects = new Manager(Estado.class);

    public Estado() {

    }

    public Estado(String nome, String sigla, Pais pais) {
        this.nome = nome;
        this.sigla = sigla;
        this.pais = pais;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getSigla() {
        return sigla;
    }

    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    public Pais getPais() {
        return pais;
    }

    public void setPais(Pais pais) {
        this.pais = pais;
    }

    public String unicode() {
        return String.format("%s [%s]", nome, pais.getNome());
    }


    // Generated by Jedi ORM
    public QuerySet<Cidade> getCidadeSet() {
        return Cidade.objects.getSet(Estado.class, this.id);
    }
}
